<?php
/**
 * @file
 *
 * Selecting all children of a given taxonomy term can be a pain.
 * This module makes it easier to do this, by maintaining a complete list of
 * edges for each term using the adjecency matrix graph theory.
 *
 * Currently only MySQL is supported.
 *
 * Example of getting all children from tid:14
 *
 * SELECT tid FROM {taxonomy_term_edge} WHERE parent = 14
 *
 * NOTE: Multiple parents are somewhat supported.
 *
 * @todo Convert to ANSI SQL (if possible) for compatibility with other databases than MySQL
 * @todo Use batch API for rebuild edges manually.
 * @todo Integrate with Views.
 *
 * @see README.txt
 */

/**
 * Fail safe for avoiding infite loops when rebuilding edges.
 */
define('TAXONOMY_EDGE_MAX_DEPTH', 100);




// ---------- HOOKS ----------

/**
 * Implements hook_help().
 */
function taxonomy_edge_help($section) {
  switch ($section) {
    case 'admin/help#taxonomy_edge':
      // Return a line-break version of the module README.txt
      return check_markup(file_get_contents( dirname(__FILE__) . "/README.txt"));
  }
}

/**
 * Implementation of hook_perm().
 */
function taxonomy_edge_perm() {
  return array('administer taxonomy edge');
}

/**
 * Implementation of hook_menu().
 */
function taxonomy_edge_menu() {
  $items = array();

  // settings page
  $items['admin/structure/taxonomy/edge'] = array(
    'title'            => 'Edge',
    'description'      => 'Administer taxonomy edges',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('taxonomy_edge_settings_form'),
    'access arguments' => array('administer taxonomy edge'),
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'taxonomy_edge.pages.inc'
  );

  return $items;
}

/**
 * Implementation of hook_taxonomy().
 *
 * Maintain edges upon taxonomy manipulation
 */
function taxonomy_edge_taxonomy($op, $type, $array = NULL) {
  $array = (array)$array;
  switch ($type) {
    case 'term':
      switch ($op) {
        case 'insert':
          _taxonomy_edge_insert($array['tid'], $array['parent']);
          break;
        case 'update':
          _taxonomy_edge_update($array['tid'], $array['parent']);
          break;
        case 'delete':
          _taxonomy_edge_delete($array['tid']);
          break;
      }
  }
}

/**
 * Implementation of hook_cronapi().
 * Regularly rebuild the edge list
 */
function taxonomy_edge_cronapi($op, $job = NULL) {
  switch ($op) {
    case 'list':
      return array('taxonomy_edge_rebuild_cron' => 'Rebuild taxonomy edges');
    case 'rule':
      return '0 2 * * *';
  }
}




// ---------- PRIVATE HELPER FUNCTIONS ----------

/**
 * Rebuild edges
 */
function taxonomy_edge_rebuild_cron() {
  $context = array();
  $rows = taxonomy_edge_rebuild($context);
  if (is_numeric($rows)) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}

/**
 * Start batch job for rebuild of edges
 */
function taxonomy_edge_rebuild_batch() {
  $batch = array(
    'operations' => array(
      array('taxonomy_edge_rebuild', array())
    ),
    'finished' => 'taxonomy_edge_rebuild_finished',
    'file' => drupal_get_path('module', 'taxonomy_edge') . '/taxonomy_edge.pages.inc',
    'title' => t('Rebuilding taxonomy edges'),
    'init_message' => t('Rebuilding taxonomy edges'),
  );
  batch_set($batch);
}

/**
 * Finished function for rebuild tree batch operation.
 *
 * @param type $success
 * @param type $result
 * @param type $operations 
 */
function taxonomy_edge_rebuild_finished($success, $result, $operations) {
  if ($success) {
    drupal_set_message(t('Taxonomy edges rebuilt: %rows processed with depth %depth in %time seconds', 
      array('%rows' => $result['rows'], '%depth' => $result['depth'], '%time' => sprintf("%.03f", $result['time'])))
    );
  }
  else {
    drupal_set_message(t('Taxonomy edges rebuilt: FAILED'), 'error');
  }
}

/**
 * Insert edges for a term.
 *
 * @param $tid
 *   Term ID.
 * @param $parents
 *   Parent term IDs, either one integer or an array of integers.
 * @return integer/boolean
 *   Number of rows updated or FALSE if failed.
 */
function _taxonomy_edge_insert($tid, $parents) {
  if (!is_array($parents)) {
    $parents = array($parents);
  }

  watchdog('taxonomy_edge', 'Inserting taxonomy-edge for %tid [%parent]', array('%tid' => $tid, '%parent' => join(',', $parents)), WATCHDOG_DEBUG);

  if ($tid > 0) {
    if (function_exists('db_start_transaction')) {
      db_start_transaction();
    }

    $rows += db_query("INSERT INTO {taxonomy_term_edge} (tid, parent, distance) VALUES(:tid1, :tid2, 0)", array(':tid1' => $tid, ':tid2' => $tid))->rowCount();

    foreach ($parents as $parent) {
      // @todo Investigate missing argument!
      $rows += db_query("
        INSERT INTO {taxonomy_term_edge} (tid, parent, distance)
        SELECT :tid, e1.parent, e1.distance + 1
        FROM {taxonomy_term_edge} e1
        LEFT JOIN {taxonomy_term_edge} e2 ON e2.tid = :tid AND e2.parent = e1.parent
        WHERE e1.tid = :parent
        AND e2.tid IS NULL
      ", array(':tid' => $tid, ':parent' => $parent))->rowCount();
    }
    if (function_exists('db_end_transaction')) {
      db_end_transaction();
    }
    return $rows;
  }
  else {
    watchdog('taxonomy_edge', 'Invalid term-id (%tid) received', array('%tid' => $tid), WATCHDOG_ERROR);
    return FALSE;
  }
}

/**
 * Move term in the edge list.
 *
 * @param $tid
 *   Term ID.
 * @param $parents
 *   Parent term IDs, either one integer or an array of integers.
 */
function _taxonomy_edge_update($tid, $parents) {
  if (!is_array($parents)) {
    $parents = array($parents);
  }

  watchdog('taxonomy_edge', 'Updating taxonomy-edge for %tid [%parent]', array('%tid' => $tid, '%parent' => join(',', $parents)), WATCHDOG_DEBUG);

  if (function_exists('db_start_transaction')) {
    db_start_transaction();
  }

  // Find invalid edges after move
  db_query("CREATE TEMPORARY TABLE {term_edge_delete} (tid INT(11), parent INT(11), PRIMARY KEY (`tid`, `parent`))");
  db_query("
    INSERT INTO {term_edge_delete}
    SELECT DISTINCT te2.tid, te2.parent
    FROM {taxonomy_term_edge} te1
    INNER JOIN {taxonomy_term_edge} te2 ON te1.tid = te2.tid
    WHERE te1.parent = :tid AND te2.distance > te1.distance
  ", array(':tid' => $tid));

  // Delete those edges
  db_query("
    DELETE e.*
    FROM {taxonomy_term_edge} e
    JOIN {term_edge_delete} ed ON e.tid = ed.tid AND e.parent = ed.parent
  ");

  // Insert new and correct edges
  $placeholders = db_placeholders($parents, 'int');
  $args = $parents;
  $args[] = $tid;
  db_query("
    INSERT INTO {taxonomy_term_edge} (tid, parent, distance)
    SELECT te2.tid, te1.parent, te1.distance + te2.distance + 1
    FROM {taxonomy_term_edge} te1
    INNER JOIN {taxonomy_term_edge} te2 ON te1.tid IN (" . $placeholders . ") AND te2.parent = :parent
    LEFT JOIN {taxonomy_term_edge} te3 ON te2.tid = te3.tid AND te1.parent = te3.parent
    WHERE te3.tid IS NULL
  ", $args);

  // Clean up
  db_query("DROP TEMPORARY TABLE {term_edge_delete}");

  if (function_exists('db_end_transaction')) {
    db_end_transaction();
  }
}

/**
 * Delete edges
 *
 * @param $tid
 *   Term ID.
 */
function _taxonomy_edge_delete($tid) {
  db_query("DELETE FROM {taxonomy_term_edge} WHERE tid = :tid OR parent = :tid", array('tid' => $tid));
}




// ---------- PUBLIC HELPER FUNCTIONS ----------

/**
 * Rebuild entire edge list.
 *
 * @return integer
 *   Total number of rows inserted.
 */
function taxonomy_edge_rebuild(&$context) {
  $depth = 0;
  $max_depth = variable_get('taxonomy_edge_max_depth', TAXONOMY_EDGE_MAX_DEPTH);

  $time = microtime(TRUE);
  set_time_limit(86400);

  if (function_exists('db_start_transaction')) {
    db_start_transaction();
    // TRUNCATE is not transaction safe on some DB's (at least MySQL).
    db_query("DELETE FROM {taxonomy_term_edge}");
  }
  else {
    // Use TRUNCATE if possible, much faster than DELETE FROM (if there are many rows).
    db_query("TRUNCATE {taxonomy_term_edge}");
  }

  $total_rows = db_query("
    INSERT INTO {taxonomy_term_edge} (tid, parent, distance)
    SELECT h.tid, h.tid, 0
    FROM {taxonomy_term_hierarchy} h
    LEFT JOIN {taxonomy_term_edge} e ON e.tid = h.tid AND e.parent = h.tid
    WHERE h.tid <> 0
    AND h.tid <> h.parent
    AND e.tid IS NULL
  ")->rowCount();
  $context['message'] = t('Processed %rows rows - current depth: %depth', array('%rows' => $total_rows, '%depth' => $depth));
  $context['finished'] = 0.5;
  
  while ($max_depth-- > 0) {
    $result = db_query("
      INSERT INTO {taxonomy_term_edge} (tid, parent, distance)
      SELECT h.tid, e.parent, :depth + 1
      FROM {taxonomy_term_hierarchy} h
      INNER JOIN {taxonomy_term_edge} e ON e.tid = h.parent
      LEFT JOIN {taxonomy_term_edge} e2 ON e2.tid = h.tid AND e2.parent = e.parent
      WHERE e.distance = :depth
      AND h.tid <> 0
      AND h.tid <> h.parent
      AND e2.tid IS NULL
    ", array('depth' => $depth));

    if (!$result) {
      break;
    }
    $depth++;

    $rows = $result->rowCount();
    if ($rows <= 0) {
      break;
    }

    $total_rows += $rows;
    $context['message'] = t('Processed %rows rows - current depth: %depth', array('%rows' => $total_rows, '%depth' => $depth));
    $context['finished'] += (1 - $context['finished']) / 2;
  }
  $context['finished'] = 1;

  if (function_exists('db_end_transaction')) {
    db_end_transaction();
  }
  $context['results'] = array('rows' => $total_rows, 'depth' => $depth - 1, 'time' => microtime(TRUE) - $time);
  
  return $total_rows;
}

/**
 * Get parent from edge list.
 *
 * @param $tid
 *   term id to get parent from.
 * @return array
 *   array of term ids.
 */
function taxonomy_edge_get_parents($tid) {
  $parents = array();
  $result = db_query("
    SELECT e.parent AS tid, d.name
    FROM {taxonomy_term_edge} e JOIN {taxonomy_term_data} d ON e.parent = d.tid
    WHERE e.tid = :tid
    AND e.distance > 0
    ORDER BY e.distance
  ", array($tid));
  while ($parent = db_fetch_object($result)) {
    $parents[] = $parent;
  }
  return $parents;
}

/**
 * Get top term id.
 *
 * @param $tid
 *   Term ID to get top term ID from.
 * @return integer
 *   Top term ID.
 */
function taxonomy_edge_get_top_tid($tid) {
  return db_result(db_query("
    SELECT h.tid
    FROM {taxonomy_term_edge} te
    INNER JOIN {taxonomy_term_hierarchy} h ON te.parent = h.tid
    WHERE h.parent = 0
    AND te.tid = :tid
  ", array($tid)));
}

/**
 * Reimplementation of taxonomy_select_nodes().
 * Uses the Taxonomy Edge table instead of cpu/mem (mostly mem) hungry taxonomy_get_tree().
 * @note This function also fixes the "broken" default order by from the taxonomy_select_nodes() function,
 *       by added "n.nid" to the ORDER BY clause. This is ensure consistent results on each query.
 *
 * @see taxonomy_select_nodes()
 */
function taxonomy_edge_taxonomy_select_nodes($tids = array(), $operator = 'or', $depth = 0, $pager = TRUE, $order = 'n.sticky DESC, n.created DESC, n.nid DESC') {
  // Fix broken default order by the Taxonomy Module.
  // Ordering without a unique key could result in incosistent result sets,
  // depending on which index (if any) the database decides to use for the query.
  switch ($order) {
    case 'n.sticky DESC, n.created DESC':
      $order .= ', n.nid DESC';
      break;
    case 'n.sticky ASC, n.created ASC':
      $order .= ', n.nid ASC';
      break;
  }

  // If possible, use optimize by using GROUP BY instead of DISTINCT.
  // This is what the idx_taxonomy_edge index is used for.
  $group_by = '';
  $distinct = 'DISTINCT(n.nid)';
  switch ($order) {
    case 'n.sticky DESC, n.created DESC, n.nid DESC':
    case 'n.sticky ASC, n.created ASC, n.nid ASC':
      $group_by = ' GROUP BY n.sticky, n.created, n.nid';
      $distinct = 'n.nid';
      break;
    case 'n.created DESC, n.nid DESC':
    case 'n.created ASC, n.nid ASC':
      $group_by = ' GROUP BY n.created, n.nid';
      $distinct = 'n.nid';
      break;
  }

  if (count($tids) > 0) {
    if ($operator == 'or') {
      $args = $tids;
      $placeholders = db_placeholders($args, 'int');
      if ($depth === 'all') {
        $sql = 'SELECT ' . $distinct . ', n.sticky, n.title, n.created FROM {node} n INNER JOIN {term_node} tn ON n.vid = tn.vid JOIN {taxonomy_term_edge} te ON tn.tid = te.tid WHERE te.parent IN(' . $placeholders . ') AND n.status = 1 ' . $group_by . ' ORDER BY ' . $order;
        $sql_count = 'SELECT COUNT(DISTINCT n.nid) FROM {node} n INNER JOIN {term_node} tn ON n.vid = tn.vid JOIN {taxonomy_term_edge} te ON tn.tid = te.tid WHERE te.parent IN(' . $placeholders . ') AND n.status = 1';
      }
      else {
        $sql = 'SELECT ' . $distinct . ', n.sticky, n.title, n.created FROM {node} n INNER JOIN {term_node} tn ON n.vid = tn.vid JOIN {taxonomy_term_edge} te ON tn.tid = te.tid WHERE te.parent IN(' . $placeholders . ') AND te.distance <= %d AND n.status = 1 ' . $group_by . ' ORDER BY ' . $order;
        $sql_count = 'SELECT COUNT(DISTINCT n.nid) FROM {node} n INNER JOIN {term_node} tn ON n.vid = tn.vid JOIN {taxonomy_term_edge} te ON tn.tid = te.tid WHERE te.parent IN(' . $placeholders . ') AND te.distance <= %d AND n.status = 1';
        $args[] = $depth;
      }
    }
    else {
      $join = '';
      $args = array();
      foreach ($tids as $index => $tid) {
        $join .= ' INNER JOIN {term_node} tn' . $index . ' ON n.vid = tn' . $index . '.vid';
        $join .= ' INNER JOIN {taxonomy_term_edge} te' . $index . ' ON tn' . $index . '.tid = te'. $index . '.tid AND te' . $index . '.parent = %d';
        $args[] = $tid;
        if ($depth !== 'all') {
          $join .= ' AND te'. $index .'.distance <= %d';
          $args[] = $depth;
        }
      }
      $sql = 'SELECT ' . $distinct . ', n.sticky, n.title, n.created FROM {node} n ' . $join . ' WHERE n.status = 1 ' . $group_by . ' ORDER BY ' . $order;
      $sql_count = 'SELECT COUNT(DISTINCT n.nid) FROM {node} n ' . $join . ' WHERE n.status = 1';
    }
    $sql = db_rewrite_sql($sql);
    if ($pager) {
      $sql_count = db_rewrite_sql($sql_count);
      $result = pager_query($sql, variable_get('default_nodes_main', 10), 0, $sql_count, $args);
    }
    else {
      $result = db_query_range($sql, $args, 0, variable_get('feed_default_items', 10));
    }
  }

  return $result;
}

/**
 * Reimplementation of taxonomy_get_tree().
 * Limit db fetch to only specified parent and max_depth.
 * @see taxonomy_get_tree()
 */
function taxonomy_edge_get_tree($vid, $parent = 0, $max_depth = NULL, $load_entities = FALSE) {
  $children = &drupal_static('taxonomy_get_tree', array());
  $parents = &drupal_static('taxonomy_get_tree' . ':parents', array());
  $terms = &drupal_static('taxonomy_get_tree' . ':terms', array());

  // We cache trees, so it's not CPU-intensive to call get_tree() on a term
  // and its children, too.
  if (!isset($children[$vid][$parent])) {
    $children[$vid][$parent] = array();

    $query = db_select('taxonomy_term_data', 't');
    $query->join('taxonomy_term_hierarchy', 'h', 'h.tid = t.tid');
    $query
      ->addTag('translatable')
      ->addTag('term_access')
      ->fields('t')
      ->fields('h', array('parent'))
      ->condition('t.vid', $vid)
      ->orderBy('t.weight')
      ->orderBy('t.name');

    if ($parent) {
      $query->join('taxonomy_term_edge', 'e', 'e.tid = t.tid');
      $query->condition('e.parent', $parent);
    }

    $result = $query->execute();

    foreach ($result as $term) {
      if (!isset($terms[$vid][$term->tid])) {
        $children[$vid][$term->parent][] = $term->tid;
        $parents[$vid][$term->tid][] = $term->parent;
        $terms[$vid][$term->tid] = $term;
      }
    }
  }

  // Load full entities, if necessary. The entity controller statically
  // caches the results.
  if ($load_entities) {
    $term_entities = taxonomy_term_load_multiple(array_keys($terms[$vid]));
  }

  $max_depth = (!isset($max_depth)) ? count($children[$vid]) : $max_depth;
  $tree = array();

  // Keeps track of the parents we have to process, the last entry is used
  // for the next processing step.
  $process_parents = array();
  $process_parents[] = $parent;

  // Loops over the parent terms and adds its children to the tree array.
  // Uses a loop instead of a recursion, because it's more efficient.
  while (count($process_parents)) {
    $parent = array_pop($process_parents);
    // The number of parents determines the current depth.
    $depth = count($process_parents);
    if ($max_depth > $depth && !empty($children[$vid][$parent])) {
      $has_children = FALSE;
      $child = current($children[$vid][$parent]);
      do {
        if (empty($child)) {
          break;
        }
        $term = $load_entities ? $term_entities[$child] : $terms[$vid][$child];
        if (count($parents[$vid][$term->tid]) > 1) {
          // We have a term with multi parents here. Clone the term,
          // so that the depth attribute remains correct.
          $term = clone $term;
        }
        $term->depth = $depth;
        unset($term->parent);
        $term->parents = array_values($parents[$vid][$term->tid]);
        $tree[] = $term;
        if (!empty($children[$vid][$term->tid])) {
          $has_children = TRUE;

          // We have to continue with this parent later.
          $process_parents[] = $parent;
          // Use the current term as parent for the next iteration.
          $process_parents[] = $term->tid;

          // Reset pointers for child lists because we step in there more often
          // with multi parents.
          reset($children[$vid][$term->tid]);
          // Move pointer so that we get the correct term the next time.
          next($children[$vid][$parent]);
          break;
        }
      } while ($child = next($children[$vid][$parent]));

      if (!$has_children) {
        // We processed all terms in this hierarchy-level, reset pointer
        // so that this function works the next time it gets called.
        reset($children[$vid][$parent]);
      }
    }
  }

  return $tree;
}
